### ISSUE TITLE
sudoers: double negation via User_Alias does not work as expected

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#180]
relevant test

https://github.com/memorysafety/sudo-rs/blob/6825e1234323da82c804a58214266db9b035eb6e/test-framework/sudo-compliance-tests/src/sudoers/user_list.rs#L207-L238

given the above sudoers file

sudo-rs:  `sudo true` as `ghost` fails with `Error: Authentication("no permission")`

ogsudo: that operations works

**Comment by squell** [comment]
I've consulted with "upstream" about this issue.

If it turns out that this special interpretation of negation is an important feature of aliases, I think we can implement it by--after doing the topological sort of aliases we already do, i.e. without having to do it recursively--by just substituting the alias-mentions in the abstract syntax tree (distributing the negations over the elements of the alias definition if necessary).

**Comment by squell** [comment]
There is a snag, e.g.
```
User_Alias FOO = !ghost
ALL, FOO host = ALL
```
Would allow everybody except `ghost` to run something in ogsudo, but would allow everyone to run a command using `sudo-rs`. So probably the safest/simplest way is to implement sudo's alias handling.
