### ISSUE TITLE
too many dependencies for a setuid program

### ISSUE THREAD

**Issue by arogge** [memorysafety/sudo-rs#264]
When looking at the `Cargo.lock`, I see a lot of dependencies:
```
$ grep -c 'source = "registry' Cargo.lock
103
```
With more than 100 other packages used, there is no feasible way to manage the security of the resulting program.
If any dependency package is compromised, we may end up with a compromised `sudo` or `su`. Unless you use a trusted toolchain and a limited number of really required and well maintained dependencies, people will have trust issues.

**Comment by rnijveld** [comment]
Checking the cargo.lock file is generally a bad indicator of the number of dependencies in the compiled sudo-rs artifacts. Lots of these are related to testing and build-time dependencies (i.e. bindgen, syn, etc). We are aware that we currently have a relatively large set of indirect dependencies, and we’ll keep that in mind, but we preferred to start with having at least all the functionality there and then going for a more optimized setup (with the possibility of fewer dependencies, or at least with a process in place for managing them) once we have an outline of the entire code flow.

There is of course a balance to be found somewhere, as reinventing every wheel will almost certainly result in more bugs than having some wheels invented for us already.

**Comment by arogge** [comment]
I totally agree that re-inventing the wheel is usually not a good thing.
Could you elaborate on how a user can easily determine which dependencies are actually compiled into the resulting artifacts and which ones are just used for testing and building?

**Comment by NobodyXu** [comment]
> I totally agree that re-inventing the wheel is usually not a good thing.
> 
> Could you elaborate on how a user can easily determine which dependencies are actually compiled into the resulting artifacts and which ones are just used for testing and building?

You can run "cargo tree", it will show all deps and include info on whether they are regular dep, build dep or dev dep.

**Comment by NobodyXu** [comment]
@arogge Also note that proc-macro are not included in the final bin.

They are used to generate code which is included in the final binary.

**Comment by marlonbaeten** [comment]
Currently the only direct run-time dependencies are:

- libc
- glob
- signal-hook-registry
- env_logger
- log
- syslog

We have plans removing our dependency on syslog, which will remove the bulk of (indirect) dependencies we have right now.

We have carefully evaluated the necessity of the remaining dependencies.

I think this is a really acceptable list with from the perspective of both audibility and maintenance.

Closing this issue since I think we addresses the concerns.

**Comment by stewartsmith** [comment]
I love that the list of dependencies appears to be shrinking!

I wanted to add some context from a Linux Distribution maintenance point of view.

One of the challenges when packaging for a Linux distribution with long term support (for example, packaging for Amazon Linux) is what that dependency graph looks like and the maintenance story of each individual component, including what the API and ABI compatibility story is for them. This gets increasingly interesting as you get to a smaller and smaller "core" set of packages that you pretty much *must* have on any image. For `sudo`, it's in base AMIs but not containers, but that is still a significant install base.

From a compiled programming language ecosystem point of view, Rust and Go are particularly problematic due to their nature of statically linking bundled dependencies. It makes the evaluation of CVEs in the dependencies a much larger job, and even if not affected, security scanners have gotten wise to what versions of dependencies and compilers are used, and will report on them - so you generally have to rebuild everything anyway, if you want to avoid the large number of questions and customer angst from scary findings from security scanners.

For comparison, the BuildRequires for the `sudo` RPM in Amazon Linux 2023 is:
```
audit-libs-devel
bison
flex
gettext
groff
libcap-devel
libselinux-devel
libtool
make
openldap-devel
openssl-devel
pam-devel
python3-devel
sendmail
zlib-devel
```

Which already looks insanely large, and ends up pulling 113 extra packages into the buildroot for the `sudo` RPM.

From the last time I tried, `sudo-rs` brought in ~116 crates, but now appears to be much smaller, something like this:
```
$ cargo tree
sudo-rs v0.2.0-dev.20230627
├── glob v0.3.1
├── libc v0.2.147
├── log v0.4.19
├── signal-hook v0.3.15
│   ├── libc v0.2.147
│   └── signal-hook-registry v1.4.1
│       └── libc v0.2.147
│   [build-dependencies]
│   └── cc v1.0.79
└── signal-hook-registry v1.4.1 (*)
```

which I think looks pretty nice and minimal, and doesn't scare me too much as a distro maintainer.
