### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by dlorenc** [memorysafety/sudo-rs#469]
**Describe the feature you'd like see implemented in `sudo-rs`**
A tagged release, even if it's alpha.

**What problem can be solved with this feature?**
A tagged release makes it much easier for folks to package. I'd love to package and ship these tools with Wolfi, a Linux distro I maintain for containers, but it's easier to do that with a tagged release than just randomly picking a commit.

**Describe alternatives you've considered**
Are you sure this problem cannot be solved by an already existing feature? You could also add any alternative solutions or features you've considered.

**Additional context**

**Comment by squell** [comment]
Thanks for reaching out!

This is something we have discussed internally recently and is something we were planning to start doing really soon since it also makes it easier to dog food sudo-rs ourselves. These will probably be weekly or bi-weekly tags. Of course, the initial tagged version will still have the `SUDO_RS_IS_UNSTABLE` disclaimer and will be meant for trial purposes use only.
