### ISSUE TITLE
sudoers does not support relative paths in `@include`

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#673]
https://github.com/memorysafety/sudo-rs/blob/cb84e826510ba024342ac3ff34b7f99f9c6bb9fd/test-framework/sudo-compliance-tests/src/sudoers/include.rs#L6-L14

**Comment by squell** [comment]
Note: this is a typical issue that would be worthy of a CVE if we would be outside the alpha development stage, since it will try to open 'sudoers2' in the directory sudo is run from (it still would have to be owned by root, so not a *terrible* security risk, but still grants the user control over the sudoers file and that is not what should happen).
