### ISSUE TITLE
sudoers/@include: does not expand `%h`

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#676]
relevant test

https://github.com/memorysafety/sudo-rs/blob/5c19029b0234d3c4d4417871ccebabd035e84c68/test-framework/sudo-compliance-tests/src/sudoers/include.rs#L224-L234

`man sudoers` indicates that `%h` is to be expanded to the hostname of the invoking user

**Comment by squell** [comment]
Since this was a milestone 4 issue and we are still in the wrap-up of milestone 3, we haven't discussed this issue internally yet. But now that we have an implementation of `%h` thanks to @xy2i, someone pointed out that this change adds a bit of (functional) complexity by making the interpretation of a sudoers file "dynamic" instead of "static", and whether the use case for that is common enough to include it (with respect to the "[criteria for inclusion](https://github.com/memorysafety/sudo-rs/blob/main/CONTRIBUTING.md)"), compared to other mechanisms to achieve similar results (like provisioning with Ansible).

@japaric, @xy2i, any thoughts on how "common" the use of the `%h`-feature is nowadays?

**Comment by xy2i** [comment]
It seems to not have much use, browsing the sudo issue tracker and sysadmin reddit. We could error out if we encounter it.
