### ISSUE TITLE
Sudo on windows?

### ISSUE THREAD

**Issue by codeitlikemiley** [memorysafety/sudo-rs#745]
I understand this is a re-write of sudo on linux , unix or bsd distributions.

I just wonder if this is supporting sudo for windows
or or like perform something similar like 
running as Administrator 
or
runAs
or
https://github.com/gerardog/gsudo

It would be great if this would be cross-platform

**Comment by rnijveld** [comment]
To add a little more to this: it is even highly unlikely that we could even build something like sudo in Windows, because UAC (User Account control) is built directly into Windows and probably has no exposed API that we could rely on. Furthermore, the concepts that Windows uses to differentiate between privileged and unpriviliged users are entirely different than what is common on Linux, BSD and other unix-like systems, which makes supporting Windows virtually impossible. Of course if you use the linux subsystem for windows, you can run our implementation on top of that, but only within that context, not as a general privilige acquisition tool for general usage.
