### ISSUE TITLE
"sudo must be owned by uid 0 and have the setuid bit set" error with sudo-rs, no error with sudo

### ISSUE THREAD

**Issue by 41Leahcim** [memorysafety/sudo-rs#785]
**Describe the bug**
When I try to use sudo-rs, I get the following error:
`sudo-rs: sudo must be owned by uid 0 and have the setuid bit set
 -> error refreshing databases - exit status 1`
I don't get this error with the original sudo written in C.

**To Reproduce**
1. Install sudo-rs with `cargo install sudo-rs`
2. Run the following command 'yay -Syu'
3. See error

**Expected behavior**
Yay should update my software, but can't because it can't get root access.

**Environment (please complete the following information):**
 - Linux distribution: Arch Linux
 - `sudo-rs` version: 0.2.1

**Additional context**

**Comment by marlonbaeten** [comment]
Thanks for your report Michael.

sudo-rs is a "setuid" program, the binary needs to be owned by `root` and have the "setuid" flag set in order to escalate privileges, just like the original sudo. See https://github.com/memorysafety/sudo-rs/blob/main/README.md?plain=1#L31

You can fix this by running the following as root:
```sh
chown root /path/to/sudo-rs
chmod 4755 /path/to/sudo-rs
```
